# Generated by Django 5.2.8 on 2025-11-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Website URL')),
                ('status', models.IntegerField(default=200, verbose_name='HTTP Status')),
                ('response_time', models.FloatField(verbose_name='Response Time (s)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Check Time')),
                ('is_up', models.BooleanField(default=True, verbose_name='Site Available')),
            ],
        ),
    ]
